server:
  listen: 0.0.0.0:2222
  
katago:
  bins:
    - name: katago-1.4.5 # name it any name
      path: /usr/local/bin/katago # the katago bin file location
      # runner: aistudio-runner
    - name: katago-1.5.0 # name it any name
      path: /Users/wangjinggang/gochess/ikatago-credentials/aistudio/katago.1.5.0 # the katago bin file location
      runner: aistudio-runner # optional, only baidu aistudio needs this. 
  weights:
    - name: 20b
      path: /Users/wangjinggang/gochess/katago/model.bin.gz
  configs:
    - name: 1po
      path: /Users/wangjinggang/gochess/remote/katago_1v.cfg
  defaultBinName: katago-1.4.5
  defaultWeightName: 20b
  defaultConfigName: 1po
  customConfigDir: ./data

use_nat: direct

nats: # only the name configured in "user_nat" will be used
  frpBykinfkong:
    type: frp
    config_file: ./config/frpc.ini
  frpBynatfrp:
    type: frp
    config_file: ./config/nat-frpc.ini
  direct: 
    type: direct
    host: 192.168.1.222 # the host or ip that you can connect this server directly
    port: 2222 # generally, it should equals to the server listen port

users:
  file: ./userlist.txt