server:
  listen: 0.0.0.0:2223
  
katago:
  bins:
    - name: mock-katago # name it any name
      path: ./data/bins/run-mock-katago.sh # the katago bin file location
      description: The mock katago
    - name: test # name it any name
      path: ./data/bins/test.sh
      description: for any command test
  weights:
    - name: 20b
      path: ./data/weights/model.bin.gz
  configs:
    - name: default
      path: ./data/configs/default_gtp.cfg
  defaultBinName: mock-katago
  defaultWeightName: 20b
  defaultConfigName: default
  customConfigDir: ./data
  enableWeightsDetectionInDir: ./data/weights

gomoku:
  bins:
    - name: mock-gomoku-katago # name it any name
      path: ./gomoku-data/bins/run-mock-katago.sh # the katago bin file location
      description: The mock katago
    - name: test # name it any name
      path: ./gomoku-data/bins/test.sh
      description: for any command test
  weights:
    - name: 20b
      path: ./gomoku-data/weights/model.bin.gz
  configs:
    - name: default
      path: ./gomoku-data/configs/default_gtp.cfg
  defaultBinName: mock-gomoku-katago
  defaultWeightName: 20b
  defaultConfigName: default
  customConfigDir: ./gomoku-data
  enableWeightsDetectionInDir: ./gomoku-data/weights

use_nat: frp

nats: # only the name configured in "user_nat" will be used
  frp:
    type: frp
    config_file: ./config/frpc.txt

users:
  file: ./data/userlist.txt

report:
  url: http://localhost:4200/api/ikatago/report-log/batch

cluster:
  serverUrl: http://localhost:4200