default_katago: katago-40b

katagos:
  - name: katago-20b
    bin: katago-v1.4.5-cuda10.2-linux-x64
    weight: 20b
    conf: 500v

  - name: katago-40b
    bin: katago-v1.4.5-cuda10.2-linux-x64
    weight: 40b
    conf: 500v

bins:
  - name: katago-v1.4.5-cuda10.2-linux-x64
    from: https://github.com/lightvector/KataGo/releases/download/v1.4.5/katago-v1.4.5-cuda10.2-linux-x64.zip

weights:
  - name: 20b
    from: https://github.com/lightvector/KataGo/releases/download/v1.4.5/g170e-b20c256x2-s5303129600-d1228401921.bin.gz
  - name: 40b
    from: https://github.com/lightvector/KataGo/releases/download/v1.4.5/g170-b40c256x2-s5095420928-d1229425124.bin.gz

confs:
  - name: 500v
    from: https://raw.githubusercontent.com/lightvector/KataGo/master/cpp/configs/gtp_example.cfg

sshd:
  - listen: 2222
  - users: ./userlist.txt

use_nat_provider: nsloop

nat_providers:
  nsloop:
    token: 'xxxx'
    host: ''
    port: ''
  ngrok:
    token: 'xxxx'
  ssh:
    host: ''
    port: 22
    username: ''
    password: ''