server:
  listen: 0.0.0.0:2223
  
katago:
  bins:
    - name: mock-katago
      path: ./data/bins/mock-katago/run-mock-katago.sh
      description: v1.8.1版本的katago
  weights:
    - name: 20b
      path: ./data/weights/20b.bin.gz
      description: 20b权重
      optional: true
  configs:
    - name: default_gtp
      path: ./data/configs/default_gtp.cfg
      description: 默认配置
      optional: true
   
  defaultBinName: katago-1.8.1
  defaultWeightName: 40b
  defaultConfigName: default_gtp 
  customConfigDir: ./user-data
  enableWeightsDetectionInDir: ./data/weights

use_nat: frp

nats: # only the name configured in "user_nat" will be used
  frp:
    type: frp
    config_file: ./config/frpc.txt
  direct: 
    type: direct
    host: gpu48.mistgpu.com # the host or ip that you can connect this server directly
    port: 2222 # generally, it should equals to the server listen port

users:
  file: ./userlist.txt

report:
  url: http://8.130.167.86:8080/api/ikatago/report-log/batch